variable azure_region {}
variable resource_group_name {}
variable virtual_network_name {}
variable vnet_cidr {}
variable subnet1_name {}
variable subnet1_cidr {}
variable subnet2_name {}
variable subnet2_cidr {}
variable azure_nsg_name {}
variable azure_pip {}
variable azure_nic {}
